networks:
  default:
    driver: bridge
  infra-net:
    external: true

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

services:
  # MySQL
  mysql:
    extends:
      file: ./infra/mysql/compose.yml
      service: mysql

  # Redis
  redis:
    extends:
      file: ./infra/redis/compose.yml
      service: redis

  # Kafka brokers
  kafka-1:
    extends:
      file: ./infra/kafka/compose.yml
      service: kafka-1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka-1:29092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10

  kafka-2:
    extends:
      file: ./infra/kafka/compose.yml
      service: kafka-2
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka-2:29092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10

  kafka-3:
    extends:
      file: ./infra/kafka/compose.yml
      service: kafka-3
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka-3:29092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 10

    # Prometheus
  prometheus:
    extends:
      file: ./infra/monitor/compose.yml
      service: prometheus

  # Grafana
  grafana:
    extends:
      file: ./infra/monitor/compose.yml
      service: grafana

  # Node Exporter
  node-exporter:
    extends:
      file: ./infra/monitor/compose.yml
      service: node-exporter

  # Redis Exporter
  redis-exporter:
    image: oliver006/redis_exporter
    command:
      - "--redis.addr=redis:6379"
    ports:
      - "9121:9121"
    networks:
      - infra-net
    depends_on:
      - redis
    restart: always

  # Kafka Exporter
  kafka-exporter:
    image: danielqsj/kafka-exporter
    command:
      - "--kafka.server=kafka-1:29092"
      - "--kafka.server=kafka-2:29092"
      - "--kafka.server=kafka-3:29092"
      - "--kafka.version=2.8.0"
      - "--consumer"
    ports:
      - "9308:9308"
    networks:
      - infra-net
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    restart: always

  # mysql Exporter
  mysqld-exporter:
    image: prom/mysqld-exporter
    command:
      - "--config.my-cnf=/etc/mysql/.my.cnf"
    volumes:
      - ./infra/mysql/.my.cnf:/etc/mysql/.my.cnf:ro
    ports:
      - "9104:9104"
    networks:
      - infra-net
    depends_on:
      - mysql
    restart: always
